-- Spice Kart · rewrites the starter Help centre articles to match what the customer app can do today
-- (no in-app cancel / edit, no substitutions, no wallet checkout or withdrawals, support via chat).
-- Run once in Supabase → SQL Editor after supabase/support.sql. Safe to re-run.
-- Rows are matched by topic + their original starter title, so ids, views and votes are kept and
-- articles you've already renamed or added in the admin are left alone.

update public.help_articles a
   set sort = v.sort, title = v.title, subtitle = v.subtitle, body = v.body,
       steps_title = v.steps_title, steps = v.steps, note = v.note
  from (values
  ('orders', 'Where is my order?', 1, 'Where is my order?', 'Live status and arrival time',
   'Every order shows its live status — confirmed, picking, packed, out for delivery and delivered — with the time each step happened and your estimated arrival. The Track screen updates by itself as your order moves along.',
   'HOW TO TRACK', array['Tap Orders in the bottom bar.', 'Find your order under Active.', 'Tap Track to see each step and your estimated arrival.', 'Need the store? Tap the phone button on the store card to call them.'],
   'If your order is running late, Track shows RUNNING LATE. Contact support any time and we’ll chase it up for you.'),
  ('orders', 'An item is missing from my delivery', 2, 'An item is missing from my delivery', 'Report it and we’ll sort it out',
   'Sorry about that. Report it in the app and our support team will check your order and arrange a refund for anything that didn’t arrive.',
   'HOW TO REPORT IT', array['Tap your avatar on Home, then Contact support.', 'Tap Report an issue and choose Missing item.', 'Tell us which item is missing and add a photo if it helps.', 'Tap Continue to chat — we’ll reply in the same chat.'],
   'Please report missing items as soon as you can after delivery so we can check with the store.'),
  ('orders', 'Cancel or change an order', 3, 'Cancel or change an order', 'Contact us before picking starts',
   'Orders can’t be cancelled or edited in the app yet. If you need to cancel or change something, contact support as soon as possible — we can usually help until the store starts picking your groceries.',
   'TO ASK FOR A CHANGE', array['Tap your avatar on Home, then Contact support.', 'Tap Live chat.', 'Send your order number and what you’d like to change.'],
   'Orders that are already out for delivery can’t be cancelled.'),
  ('orders', 'Substitutions explained', 4, 'Ordering again', 'Reorder a past order in one tap',
   'Add everything from a past order back to your cart in one tap. Items are added at today’s prices, and anything no longer in our range is left out.',
   'TO REORDER', array['Tap Orders in the bottom bar.', 'Open Past Orders.', 'Tap Reorder on the order you want.', 'Check your cart, then place the order.'],
   ''),
  ('delivery', 'Delivery times & fees', 1, 'Delivery times & fees', 'Express vs scheduled',
   'Express delivery arrives in about {eta_minutes} minutes while the store is open. Scheduled delivery lets you pick a delivery window up to {book_ahead_days} days ahead.',
   'FEES AT A GLANCE', array['Express: {express_fee}, free over {free_over}.', 'Scheduled: from {scheduled_fee} — each window shows its own fee.', 'Handling fee: {handling_fee} per order.', 'Every fee is shown at checkout before you place the order.'],
   'Outside store hours Express shows as Closed — choose Schedule instead.'),
  ('delivery', 'Booking a scheduled slot', 2, 'Booking a scheduled slot', 'Choose a delivery window',
   'Pick a day and a delivery window at checkout. Windows close {slot_cutoff} before they start.',
   'TO BOOK A WINDOW', array['Go to checkout.', 'Tap Schedule under delivery time.', 'Pick a day, then an available window.', 'Tap Place order.'],
   'Popular windows fill up — book early for weekends.'),
  ('delivery', 'I wasn’t home for my delivery', 3, 'I wasn’t home for my delivery', 'What to do next',
   'Missed your delivery? Contact support straight away and we’ll work out the next steps with the store.',
   'NEXT TIME', array['Keep your mobile number up to date in Personal details.', 'Keep your phone nearby around your arrival time.', 'Check Track for your estimated arrival.'],
   'You can also call the store from the Track screen.'),
  ('delivery', 'Where do you deliver?', 4, 'Where do you deliver?', 'Coverage areas',
   '{delivery_area} Add your address in the app and we’ll tell you straight away if it’s outside our delivery area.',
   'TO CHECK YOUR ADDRESS', array['Tap your avatar on Home, then Saved addresses.', 'Tap Add new address or Use my current location.', 'Enter your postcode — if we don’t deliver there yet, you’ll see a message.'],
   ''),
  ('payments', 'Why was my payment declined?', 1, 'Why was my payment declined?', 'Common causes and fixes',
   'Declines usually come from your bank — for example an expired card, a typo in the card details or not enough funds.',
   'TRY THIS', array['Check the card number, expiry and CVV under Payment methods in your account.', 'Try another method at checkout, like Apple Pay or PayID.', 'Contact your bank if the same card keeps failing.', 'Still stuck? Chat with us from Contact support.'],
   ''),
  ('payments', 'Accepted payment methods', 2, 'Accepted payment methods', 'Cards, Apple Pay, Google Pay and PayID',
   'At checkout you can pay by credit or debit card, Apple Pay, Google Pay or PayID bank transfer. The options you see depend on what your store currently accepts.',
   'TO MANAGE YOUR CARDS', array['Tap your avatar on Home, then Payment methods.', 'Tap + Add payment method to add a card.', 'Tap Set default on the card you use most.', 'Choose how to pay under Payment method at checkout.'],
   'Spice Kart Money can’t be used at checkout yet.'),
  ('payments', 'Getting a tax invoice', 3, 'Getting a tax invoice', 'Receipts for your orders',
   'Need a tax invoice or receipt for an order? Ask us in chat and we’ll send it to your email.',
   'TO GET A COPY', array['Add your email in Personal details.', 'Open Contact support and tap Live chat.', 'Send the order number you need an invoice for.'],
   ''),
  ('refunds', 'How refunds are processed', 1, 'How refunds are processed', 'Reviewed by our support team',
   'If something was missing, damaged or wrong, report it and our support team will review it and arrange your refund. We’ll keep you updated in the chat.',
   'HOW TO REQUEST A REFUND', array['Tap your avatar on Home, then Contact support.', 'Tap Report an issue and choose what went wrong.', 'Add details, and a photo if an item arrived damaged.', 'Tap Continue to chat.'],
   'Refunds go back to the payment method you used. Your bank may take 3–5 business days to show it.'),
  ('refunds', 'How do refunds to Spice Kart Money work?', 2, 'How long do refunds take?', 'Checking on a refund',
   'Once your refund is approved we’ll confirm it in your chat. It’s returned to the payment method you used for the order, and your bank may take 3–5 business days to show it.',
   'TO CHECK ON A REFUND', array['Open Contact support.', 'Under Your conversations, open the chat about your refund.', 'Still waiting after 5 business days? Send us a message in the same chat.'],
   ''),
  ('refunds', 'Damaged or expired items', 3, 'Damaged or expired items', 'Send a photo and we’ll fix it',
   'If something arrives damaged or past its use-by date, send us a photo and we’ll make it right.',
   'TO REPORT IT', array['Open Contact support and tap Report an issue.', 'Choose Damaged item.', 'Tap Attach a photo and add a short note.', 'Tap Continue to chat.'],
   'Please report it as soon as you can after delivery.'),
  ('wallet', 'What is Spice Kart Money?', 1, 'What is Spice Kart Money?', 'Your in-app balance',
   'Spice Kart Money is your in-app balance. You’ll find it on the Spice Kart Money card in your account.',
   'TO SEE YOUR BALANCE', array['Tap your avatar on Home.', 'Your balance is on the Spice Kart Money card.', 'Tap Add money to top it up.'],
   'Paying for orders with Spice Kart Money is coming soon.'),
  ('wallet', 'Earning 5% cashback', 2, 'Adding money', 'Top up your balance',
   'Top up your Spice Kart Money balance from your account in a few taps.',
   'TO ADD MONEY', array['Tap your avatar on Home, then Add money.', 'Pick $10, $25, $50 or $100, or enter a custom amount.', 'Choose how to pay.', 'Tap Confirm & add money.'],
   ''),
  ('wallet', 'Withdrawing your balance', 3, 'Questions about your balance', 'We’re here to help',
   'Balance doesn’t look right, or want to move money out? Withdrawals aren’t available in the app yet — chat with us and we’ll help.',
   'TO GET HELP', array['Open Contact support.', 'Tap Live chat.', 'Tell us what you need help with.'],
   ''),
  ('addresses', 'Can I change my address after ordering?', 1, 'Can I change my address after ordering?', 'Contact us straight away',
   'Delivery addresses can’t be changed in the app once an order is placed. Contact support straight away and we’ll see what we can do before your order leaves the store.',
   'TO ASK FOR A CHANGE', array['Open Contact support.', 'Tap Live chat.', 'Send your order number and the new address.'],
   'The new address must be inside our delivery area.'),
  ('addresses', 'Adding delivery instructions', 2, 'Adding a new address', 'Home, work and more',
   'Save your home, work or other addresses so checkout is quicker.',
   'TO ADD AN ADDRESS', array['Tap your avatar on Home, then Saved addresses.', 'Tap Add new address, or Use my current location to fill it in.', 'Enter your street, suburb, state and postcode, and choose Home, Work or Other.', 'Tap Save address.'],
   'To remove an address, press and hold it in Saved addresses.'),
  ('addresses', 'Setting a default address', 3, 'Setting a default address', 'Faster checkout',
   'Your default address is used automatically at checkout.',
   'TO SET IT', array['Tap your avatar on Home, then Saved addresses.', 'Tap Add new address.', 'Turn on Set as default address, then save.'],
   'Delivering somewhere else? Tap that address in Saved addresses before you check out.')
) v (topic, old_title, sort, title, subtitle, body, steps_title, steps, note)
 where a.topic = v.topic and (a.title = v.old_title or a.title = v.title);
